# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07a68966cf2e9eaf9bbabfa42ecbbed719b53973fbf5c476d6f6f4b2cd9432717842a295e81a31ce22672ecc08e3b0c92dd079f4c36f263754dc7ffd100ad6cf

test:
  secret_key_base: c17efdb4dc39d567b0f30ba66f5f8d34687a6991c34a33e2cfdfba71e75555bcc5dd7858951c3935d66d223f82fb93eebb27d1f851606190f8afc3c3fec30196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
